"""empty message

Revision ID: 3415b5b76b80
Revises: 708ea22de75e
Create Date: 2016-09-19 21:21:52.357701

"""

# revision identifiers, used by Alembic.
revision = '3415b5b76b80'
down_revision = '708ea22de75e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
