"""empty message

Revision ID: 46df60ae6564
Revises: 20fcf0f867c5
Create Date: 2016-09-07 21:35:18.826698

"""

# revision identifiers, used by Alembic.
revision = '46df60ae6564'
down_revision = '20fcf0f867c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
