"""empty message

Revision ID: 708ea22de75e
Revises: 88a21d5eaa67
Create Date: 2016-09-08 21:26:06.512713

"""

# revision identifiers, used by Alembic.
revision = '708ea22de75e'
down_revision = '88a21d5eaa67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
