"""empty message

Revision ID: 76b034533ebc
Revises: 132f46e4f17f
Create Date: 2016-08-31 20:49:03.190198

"""

# revision identifiers, used by Alembic.
revision = '76b034533ebc'
down_revision = '132f46e4f17f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
